@echo off
for /f "tokens=1* delims==" %%a in ('set') do (
if "%%a" NEQ "TMP" (
if "%%a" NEQ "windir" (
if "%%a" NEQ "USERPROFILE" (
if "%%a" NEQ "SystemRoot" ( set %%a=
) ) ) ) )
set OLDDIR=%CD%
cd ..
set PROCTS_DIR=%CD%
chdir /d %OLDDIR%
echo %PROCTS_DIR%
REM set MSC_INCLUDE_BASE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\
REM set SDK_INCLUDE_BASE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\
REM set MSC_BIN_BASE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\
REM set SDK_BIN_BASE=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17134.0\
REM set MSC_LIB_BASE=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\lib\
REM set SDK_LIB_BASE=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17134.0\
set MSC_INCLUDE_BASE=%PROCTS_DIR%\share000\ext\tgt\msc\win\
set SDK_INCLUDE_BASE=%PROCTS_DIR%\share000\ext\tgt\sdk\win\10.0.17134.0\include\
set MSC_BIN_BASE=%PROCTS_DIR%\share000\ext\tgt\msc\win\bin\
set SDK_BIN_BASE=%PROCTS_DIR%\share000\ext\tgt\sdk\win\10.0.17134.0\bin\
set MSC_LIB_BASE=%PROCTS_DIR%\share000\ext\tgt\msc\win\lib\
set SDK_LIB_BASE=%PROCTS_DIR%\share000\ext\tgt\sdk\win\10.0.17134.0\lib\
SET INCLUDE=%MSC_INCLUDE_BASE%include;%SDK_INCLUDE_BASE%shared;%SDK_INCLUDE_BASE%ucrt;%SDK_INCLUDE_BASE%um;
mkdir tgt
mkdir obj
mkdir tgt\fig
mkdir obj\cppmake_lib
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\cppmake_lib\winx64d
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\cppmake_lib.pdb" /Gd /TP /FC /errorReport:prompt depgraph.cpp executor.cpp ide_filter.cpp makeables.cpp path.cpp policy.cpp process.cpp stub_to_be_removed.cpp target.cpp
"%MSC_BIN_BASE%HostX86\x64\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\cppmake.lib" /NOLOGO /MACHINE:X64 %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\depgraph.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\executor.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\ide_filter.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\makeables.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\path.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\policy.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\process.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\stub_to_be_removed.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64d\target.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\cppmake_lib\winx64r
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\cppmake_lib.pdb" /Gd /TP /FC /errorReport:prompt depgraph.cpp executor.cpp ide_filter.cpp makeables.cpp path.cpp policy.cpp process.cpp stub_to_be_removed.cpp target.cpp
"%MSC_BIN_BASE%HostX86\x64\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\cppmake.lib" /NOLOGO /MACHINE:X64 /LTCG %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\depgraph.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\executor.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\ide_filter.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\makeables.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\path.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\policy.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\process.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\stub_to_be_removed.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx64r\target.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\cppmake_lib\winx86d
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\cppmake_lib.pdb" /Gd /TP /analyze- /FC /errorReport:prompt depgraph.cpp executor.cpp ide_filter.cpp makeables.cpp path.cpp policy.cpp process.cpp stub_to_be_removed.cpp target.cpp
"%MSC_BIN_BASE%HostX86\x86\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\cppmake.lib" /NOLOGO %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\depgraph.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\executor.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\ide_filter.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\makeables.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\path.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\policy.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\process.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\stub_to_be_removed.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86d\target.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\cppmake_lib\winx86r
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\cppmake_lib.pdb" /Gd /TP /analyze- /FC /errorReport:prompt depgraph.cpp executor.cpp ide_filter.cpp makeables.cpp path.cpp policy.cpp process.cpp stub_to_be_removed.cpp target.cpp
"%MSC_BIN_BASE%HostX86\x86\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\cppmake.lib" /NOLOGO /LTCG %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\depgraph.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\executor.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\ide_filter.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\makeables.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\path.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\policy.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\process.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\stub_to_be_removed.obj %PROCTS_DIR%\share000\obj\cppmake_lib\winx86r\target.obj
cd ..\..
mkdir obj\eps
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\eps\winx64d
cd comp\eps
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /D _DEBUG /D _WINDOWS /D _USRDLL /D EPS_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\eps\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\eps\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt basic_shapes.cpp eps.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\eps.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\eps.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64d\eps.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\eps\winx64d\basic_shapes.obj %PROCTS_DIR%\share000\obj\eps\winx64d\eps.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\eps\winx64r
cd comp\eps
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /GL /D NDEBUG /D _WINDOWS /D _USRDLL /D EPS_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\eps\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\eps\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt basic_shapes.cpp eps.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\eps.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\eps.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64r\eps.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\eps\winx64r\basic_shapes.obj %PROCTS_DIR%\share000\obj\eps\winx64r\eps.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\eps\winx86d
cd comp\eps
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /Oy- /D WIN32 /D _DEBUG /D _WINDOWS /D _USRDLL /D EPS_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\eps\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\eps\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt basic_shapes.cpp eps.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\eps.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\eps.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86d\eps.lib" /MACHINE:X86 /DLL %PROCTS_DIR%\share000\obj\eps\winx86d\basic_shapes.obj %PROCTS_DIR%\share000\obj\eps\winx86d\eps.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\eps\winx86r
cd comp\eps
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D _WINDOWS /D _USRDLL /D EPS_EXPORTS /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\eps\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\eps\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt basic_shapes.cpp eps.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\eps.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\eps.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86r\eps.lib" /MACHINE:X86 /SAFESEH /DLL %PROCTS_DIR%\share000\obj\eps\winx86r\basic_shapes.obj %PROCTS_DIR%\share000\obj\eps\winx86r\eps.obj
cd ..\..
mkdir obj\cppmake_test_executor
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\cppmake_test_executor\winx64d
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D TEST /D _DEBUG /D CPPMAKETESTEXECUTOR_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt executor.cpp test_executor.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\cppmake_test_executor.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\cppmake_test_executor.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64d\cppmake_test_executor.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64d\executor.obj %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64d\test_executor.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\cppmake_test_executor\winx64r
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D TEST /D NDEBUG /D CPPMAKETESTEXECUTOR_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt executor.cpp test_executor.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\cppmake_test_executor.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\cppmake_test_executor.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64r\cppmake_test_executor.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64r\executor.obj %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx64r\test_executor.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\cppmake_test_executor\winx86d
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D TEST /D WIN32 /D _DEBUG /D CPPMAKETESTEXECUTOR_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt executor.cpp test_executor.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\cppmake_test_executor.dll" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\cppmake_test_executor.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86d\cppmake_test_executor.lib" /MACHINE:X86 /DLL %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86d\executor.obj %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86d\test_executor.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\cppmake_test_executor\winx86r
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D TEST /D WIN32 /D NDEBUG /D CPPMAKETESTEXECUTOR_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt executor.cpp test_executor.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\cppmake_test_executor.dll" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\cppmake_test_executor.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86r\cppmake_test_executor.lib" /MACHINE:X86 /SAFESEH /DLL %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86r\executor.obj %PROCTS_DIR%\share000\obj\cppmake_test_executor\winx86r\test_executor.obj
cd ..\..
mkdir obj\makefile
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\makefile\winx64d
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_git" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_git\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_latex" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_latex\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_libgitssh" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_libgitssh\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_template_beamer" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_template_beamer\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_template_book" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_template_book\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_usb_repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_usb_repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\eps" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\eps\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\fig_cppmake_test_executor_nothing_to_build_uml_sd" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\fig_cppmake_test_executor_nothing_to_build_uml_sd\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\flying_start" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\flying_start\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\test" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\test\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64d\\uml" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\uml\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\makefile.dll" /INCREMENTAL /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\tgt\winx64d\ cppmake.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /INCLUDE:execute /INCLUDE:abort_execution /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\makefile.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64d\makefile.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\makefile\winx64d\\cppmake %PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_cppmake %PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_git %PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_latex %PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_libgitssh %PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_template_beamer %PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_template_book %PROCTS_DIR%\share000\obj\makefile\winx64d\\doc_usb_repo %PROCTS_DIR%\share000\obj\makefile\winx64d\\eps %PROCTS_DIR%\share000\obj\makefile\winx64d\\fig_cppmake_test_executor_nothing_to_build_uml_sd %PROCTS_DIR%\share000\obj\makefile\winx64d\\flying_start %PROCTS_DIR%\share000\obj\makefile\winx64d\\repo %PROCTS_DIR%\share000\obj\makefile\winx64d\\test %PROCTS_DIR%\share000\obj\makefile\winx64d\\uml
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\makefile\winx64r
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_git" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_git\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_latex" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_latex\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_libgitssh" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_libgitssh\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_template_beamer" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_template_beamer\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_template_book" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_template_book\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_usb_repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\doc_usb_repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\eps" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\eps\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\fig_cppmake_test_executor_nothing_to_build_uml_sd" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\fig_cppmake_test_executor_nothing_to_build_uml_sd\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\flying_start" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\flying_start\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\test" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\test\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx64r\\uml" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt comp\uml\makefile.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\makefile.dll" /INCREMENTAL:NO /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\tgt\winx64r\ cppmake.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /INCLUDE:execute /INCLUDE:abort_execution /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\makefile.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64r\makefile.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\makefile\winx64r\\cppmake %PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_cppmake %PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_git %PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_latex %PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_libgitssh %PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_template_beamer %PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_template_book %PROCTS_DIR%\share000\obj\makefile\winx64r\\doc_usb_repo %PROCTS_DIR%\share000\obj\makefile\winx64r\\eps %PROCTS_DIR%\share000\obj\makefile\winx64r\\fig_cppmake_test_executor_nothing_to_build_uml_sd %PROCTS_DIR%\share000\obj\makefile\winx64r\\flying_start %PROCTS_DIR%\share000\obj\makefile\winx64r\\repo %PROCTS_DIR%\share000\obj\makefile\winx64r\\test %PROCTS_DIR%\share000\obj\makefile\winx64r\\uml
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\makefile\winx86d
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_git" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_git\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_latex" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_latex\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_libgitssh" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_libgitssh\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_template_beamer" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_template_beamer\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_template_book" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_template_book\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_usb_repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_usb_repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\eps" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\eps\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\fig_cppmake_test_executor_nothing_to_build_uml_sd" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\fig_cppmake_test_executor_nothing_to_build_uml_sd\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\flying_start" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\flying_start\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\test" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\test\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86d\\uml" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\uml\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\makefile.dll" /INCREMENTAL /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\tgt\winx86d\ cppmake.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /INCLUDE:_execute /INCLUDE:_abort_execution /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\makefile.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86d\makefile.lib" /MACHINE:X86 /DLL %PROCTS_DIR%\share000\obj\makefile\winx86d\\cppmake %PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_cppmake %PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_git %PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_latex %PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_libgitssh %PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_template_beamer %PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_template_book %PROCTS_DIR%\share000\obj\makefile\winx86d\\doc_usb_repo %PROCTS_DIR%\share000\obj\makefile\winx86d\\eps %PROCTS_DIR%\share000\obj\makefile\winx86d\\fig_cppmake_test_executor_nothing_to_build_uml_sd %PROCTS_DIR%\share000\obj\makefile\winx86d\\flying_start %PROCTS_DIR%\share000\obj\makefile\winx86d\\repo %PROCTS_DIR%\share000\obj\makefile\winx86d\\test %PROCTS_DIR%\share000\obj\makefile\winx86d\\uml
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\makefile\winx86r
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_cppmake" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_cppmake\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_git" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_git\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_latex" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_latex\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_libgitssh" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_libgitssh\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_template_beamer" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_template_beamer\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_template_book" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_template_book\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_usb_repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\doc_usb_repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\eps" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\eps\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\fig_cppmake_test_executor_nothing_to_build_uml_sd" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\fig_cppmake_test_executor_nothing_to_build_uml_sd\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\flying_start" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\flying_start\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\repo" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\repo\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\test" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\test\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /Iintf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D MAKEFILE_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\makefile\winx86r\\uml" /Fd"%PROCTS_DIR%\share000\obj\makefile\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt comp\uml\makefile.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\makefile.dll" /INCREMENTAL:NO /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\tgt\winx86r\ cppmake.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /INCLUDE:_execute /INCLUDE:_abort_execution /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\makefile.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86r\makefile.lib" /MACHINE:X86 /SAFESEH /DLL %PROCTS_DIR%\share000\obj\makefile\winx86r\\cppmake %PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_cppmake %PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_git %PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_latex %PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_libgitssh %PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_template_beamer %PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_template_book %PROCTS_DIR%\share000\obj\makefile\winx86r\\doc_usb_repo %PROCTS_DIR%\share000\obj\makefile\winx86r\\eps %PROCTS_DIR%\share000\obj\makefile\winx86r\\fig_cppmake_test_executor_nothing_to_build_uml_sd %PROCTS_DIR%\share000\obj\makefile\winx86r\\flying_start %PROCTS_DIR%\share000\obj\makefile\winx86r\\repo %PROCTS_DIR%\share000\obj\makefile\winx86r\\test %PROCTS_DIR%\share000\obj\makefile\winx86r\\uml
mkdir obj\repo
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\repo\winx64d
cd comp\repo
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /I../../ext/intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /D "TARGET_DIR=\"winx64d\"" /D _DEBUG /D _LIB /D _DEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx64d\repo.pdb" /Gd /TP /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /I../../ext/intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /D _DEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx64d\repo.pdb" /Gd /TP /FC /errorReport:prompt parse_ssh_config.cpp repo.cpp platform_specific.cpp
"%MSC_BIN_BASE%HostX86\x64\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\repo.lib" /NOLOGO /MACHINE:X64 %PROCTS_DIR%\share000\obj\repo\winx64d\flying_start.obj %PROCTS_DIR%\share000\obj\repo\winx64d\parse_ssh_config.obj %PROCTS_DIR%\share000\obj\repo\winx64d\repo.obj %PROCTS_DIR%\share000\obj\repo\winx64d\platform_specific.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\repo\winx64r
cd comp\repo
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /I../../ext/intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /GL /D "TARGET_DIR=\"winx64r\"" /D NDEBUG /D _LIB /D NDEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx64r\repo.pdb" /Gd /TP /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /I../../ext/intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /GL /D NDEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx64r\repo.pdb" /Gd /TP /FC /errorReport:prompt parse_ssh_config.cpp repo.cpp platform_specific.cpp
"%MSC_BIN_BASE%HostX86\x64\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\repo.lib" /NOLOGO /MACHINE:X64 /LTCG %PROCTS_DIR%\share000\obj\repo\winx64r\flying_start.obj %PROCTS_DIR%\share000\obj\repo\winx64r\parse_ssh_config.obj %PROCTS_DIR%\share000\obj\repo\winx64r\repo.obj %PROCTS_DIR%\share000\obj\repo\winx64r\platform_specific.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\repo\winx86d
cd comp\repo
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /I../../ext/intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /Oy- /D "TARGET_DIR=\"winx86d\"" /D WIN32 /D _DEBUG /D _LIB /D WIN32 /D _DEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx86d\repo.pdb" /Gd /TP /analyze- /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /I../../ext/intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /Oy- /D WIN32 /D _DEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx86d\repo.pdb" /Gd /TP /analyze- /FC /errorReport:prompt parse_ssh_config.cpp repo.cpp platform_specific.cpp
"%MSC_BIN_BASE%HostX86\x86\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\repo.lib" /NOLOGO /NODEFAULTLIB:"libc.lib, libcmt.lib, msvcrt.lib, libcd.lib, msvcrtd.lib" %PROCTS_DIR%\share000\obj\repo\winx86d\flying_start.obj %PROCTS_DIR%\share000\obj\repo\winx86d\parse_ssh_config.obj %PROCTS_DIR%\share000\obj\repo\winx86d\repo.obj %PROCTS_DIR%\share000\obj\repo\winx86d\platform_specific.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\repo\winx86r
cd comp\repo
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /I../../ext/intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /Oy- /GL /D "TARGET_DIR=\"winx86r\"" /D WIN32 /D NDEBUG /D _LIB /D WIN32 /D NDEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx86r\repo.pdb" /Gd /TP /analyze- /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /I../../ext/intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D _LIB /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\repo\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\repo\winx86r\repo.pdb" /Gd /TP /analyze- /FC /errorReport:prompt parse_ssh_config.cpp repo.cpp platform_specific.cpp
"%MSC_BIN_BASE%HostX86\x86\Lib.exe" /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\repo.lib" /NOLOGO /LTCG %PROCTS_DIR%\share000\obj\repo\winx86r\flying_start.obj %PROCTS_DIR%\share000\obj\repo\winx86r\parse_ssh_config.obj %PROCTS_DIR%\share000\obj\repo\winx86r\repo.obj %PROCTS_DIR%\share000\obj\repo\winx86r\platform_specific.obj
cd ..\..
mkdir obj\uml
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\uml\winx64d
cd comp\uml
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D UML_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\uml\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\uml\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt uml.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\uml.dll" /INCREMENTAL /NOLOGO /LIBPATH:../../tgt/winx64d eps.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\uml.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64d\uml.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\uml\winx64d\uml.obj %PROCTS_DIR%\share000\tgt\winx64d\eps.lib
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\uml\winx64r
cd comp\uml
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D UML_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\uml\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\uml\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt uml.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\uml.dll" /INCREMENTAL:NO /NOLOGO /LIBPATH:../../tgt/winx64r eps.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\uml.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64r\uml.lib" /MACHINE:X64 /DLL %PROCTS_DIR%\share000\obj\uml\winx64r\uml.obj %PROCTS_DIR%\share000\tgt\winx64r\eps.lib
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\uml\winx86d
cd comp\uml
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D UML_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\uml\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\uml\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt uml.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\uml.dll" /INCREMENTAL /NOLOGO /LIBPATH:../../tgt/winx86d eps.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\uml.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86d\uml.lib" /MACHINE:X86 /DLL %PROCTS_DIR%\share000\obj\uml\winx86d\uml.obj %PROCTS_DIR%\share000\tgt\winx86d\eps.lib
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\uml\winx86r
cd comp\uml
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D UML_EXPORTS /D _WINDOWS /D _USRDLL /D _WINDLL /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\uml\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\uml\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt uml.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\uml.dll" /INCREMENTAL:NO /NOLOGO /LIBPATH:../../tgt/winx86r eps.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\uml.pdb" /SUBSYSTEM:WINDOWS /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86r\uml.lib" /MACHINE:X86 /SAFESEH /DLL %PROCTS_DIR%\share000\obj\uml\winx86r\uml.obj %PROCTS_DIR%\share000\tgt\winx86r\eps.lib
cd ..\..
mkdir obj\test
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\test\winx64d
cd comp\test
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\test\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\test\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt test.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\test.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\test.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64d\test.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\test\winx64d\test.obj %PROCTS_DIR%\share000\tgt\winx64d\cppmake_test_executor.lib
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\test\winx64r
cd comp\test
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\test\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\test\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt test.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\test.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\test.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64r\test.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\test\winx64r\test.obj %PROCTS_DIR%\share000\tgt\winx64r\cppmake_test_executor.lib
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\test\winx86d
cd comp\test
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\test\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\test\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt test.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\test.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\test.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86d\test.lib" /MACHINE:X86 %PROCTS_DIR%\share000\obj\test\winx86d\test.obj %PROCTS_DIR%\share000\tgt\winx86d\cppmake_test_executor.lib
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\test\winx86r
cd comp\test
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\test\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\test\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt test.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\test.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\test.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86r\test.lib" /MACHINE:X86 /SAFESEH %PROCTS_DIR%\share000\obj\test\winx86r\test.obj %PROCTS_DIR%\share000\tgt\winx86r\cppmake_test_executor.lib
cd ..\..
mkdir obj\cppmake_exe
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\cppmake_exe\winx64d
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../Intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D "TARGET_DIR=\"winx64d\"" /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_exe\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_exe\winx64d\vc141_exe.pdb" /Gd /TP /FC /errorReport:prompt main.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\cppmake.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\cppmake.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\obj\cppmake_exe\winx64d\cppmake.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\cppmake_exe\winx64d\main.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\cppmake_exe\winx64r
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../Intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D "TARGET_DIR=\"winx64r\"" /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_exe\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_exe\winx64r\vc141_exe.pdb" /Gd /TP /FC /errorReport:prompt main.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\cppmake.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\cppmake.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\obj\cppmake_exe\winx64r\cppmake.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\cppmake_exe\winx64r\main.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\cppmake_exe\winx86d
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../Intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D "TARGET_DIR=\"winx86d\"" /D WIN32 /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_exe\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_exe\winx86d\vc141_exe.pdb" /Gd /TP /analyze- /FC /errorReport:prompt main.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\cppmake.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\cppmake.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\obj\cppmake_exe\winx86d\cppmake.lib" /MACHINE:X86 %PROCTS_DIR%\share000\obj\cppmake_exe\winx86d\main.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\cppmake_exe\winx86r
cd comp\cppmake
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../Intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D "TARGET_DIR=\"winx86r\"" /D WIN32 /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\cppmake_exe\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\cppmake_exe\winx86r\vc141_exe.pdb" /Gd /TP /analyze- /FC /errorReport:prompt main.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\cppmake.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\cppmake.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\obj\cppmake_exe\winx86r\cppmake.lib" /MACHINE:X86 /SAFESEH %PROCTS_DIR%\share000\obj\cppmake_exe\winx86r\main.obj
cd ..\..
mkdir obj\fig_cppmake_test_executor_nothing_to_build_uml_sd
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64d
cd comp\fig_cppmake_test_executor_nothing_to_build_uml_sd
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt fig_cppmake_test_executor_nothing_to_build_uml_sd.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\fig_cppmake_test_executor_nothing_to_build_uml_sd.exe" /INCREMENTAL /NOLOGO /LIBPATH:../../tgt/winx64d eps.lib uml.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\fig_cppmake_test_executor_nothing_to_build_uml_sd.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64d\fig_cppmake_test_executor_nothing_to_build_uml_sd.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64d\fig_cppmake_test_executor_nothing_to_build_uml_sd.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64r
cd comp\fig_cppmake_test_executor_nothing_to_build_uml_sd
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /GL /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt fig_cppmake_test_executor_nothing_to_build_uml_sd.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\fig_cppmake_test_executor_nothing_to_build_uml_sd.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:../../tgt/winx64r eps.lib uml.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\fig_cppmake_test_executor_nothing_to_build_uml_sd.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64r\fig_cppmake_test_executor_nothing_to_build_uml_sd.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx64r\fig_cppmake_test_executor_nothing_to_build_uml_sd.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86d
cd comp\fig_cppmake_test_executor_nothing_to_build_uml_sd
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /ZI /nologo /W3 /WX- /diagnostics:classic /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt fig_cppmake_test_executor_nothing_to_build_uml_sd.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\fig_cppmake_test_executor_nothing_to_build_uml_sd.exe" /INCREMENTAL /NOLOGO /LIBPATH:../../tgt/winx86d eps.lib uml.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\fig_cppmake_test_executor_nothing_to_build_uml_sd.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86d\fig_cppmake_test_executor_nothing_to_build_uml_sd.lib" /MACHINE:X86 %PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86d\fig_cppmake_test_executor_nothing_to_build_uml_sd.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86r
cd comp\fig_cppmake_test_executor_nothing_to_build_uml_sd
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../intf /Zi /nologo /W3 /WX- /diagnostics:classic /sdl /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /permissive- /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt fig_cppmake_test_executor_nothing_to_build_uml_sd.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\fig_cppmake_test_executor_nothing_to_build_uml_sd.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:../../tgt/winx86r eps.lib uml.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\fig_cppmake_test_executor_nothing_to_build_uml_sd.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86r\fig_cppmake_test_executor_nothing_to_build_uml_sd.lib" /MACHINE:X86 /SAFESEH %PROCTS_DIR%\share000\obj\fig_cppmake_test_executor_nothing_to_build_uml_sd\winx86r\fig_cppmake_test_executor_nothing_to_build_uml_sd.obj
cd ..\..
mkdir obj\flying_start
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64d
mkdir obj\flying_start\winx64d
cd comp\flying_start
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../../share000/intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /D _DEBUG /D _CONSOLE /D "TARGET_DIR=\"winx64d\"" /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\flying_start\winx64d\\" /Fd"%PROCTS_DIR%\share000\obj\flying_start\winx64d\vc141.pdb" /Gd /TP /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64d\flying_start_share000.exe" /INCREMENTAL /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/git2/winx64d /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/ssh2/winx64d /LIBPATH:%PROCTS_DIR%\share000\../share000/tgt/winx64d repo.lib git2.lib libssh2.lib crypt32.lib rpcrt4.lib winhttp.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx64d\flying_start_share000.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64d\flying_start_share000.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\flying_start\winx64d\flying_start.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x64;%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x64;
SET LIB=%MSC_LIB_BASE%x64;%SDK_LIB_BASE%ucrt\x64;%SDK_LIB_BASE%um\x64;
mkdir tgt\winx64r
mkdir obj\flying_start\winx64r
cd comp\flying_start
"%MSC_BIN_BASE%HostX86\x64\CL.exe" /c /I../../../share000/intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /GL /D NDEBUG /D _CONSOLE /D "TARGET_DIR=\"winx64r\"" /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\flying_start\winx64r\\" /Fd"%PROCTS_DIR%\share000\obj\flying_start\winx64r\vc141.pdb" /Gd /TP /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x64\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx64r\flying_start_share000.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/git2/winx64r /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/ssh2/winx64r /LIBPATH:%PROCTS_DIR%\share000\../share000/tgt/winx64r repo.lib git2.lib libssh2.lib crypt32.lib rpcrt4.lib winhttp.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"%PROCTS_DIR%\share000\tgt\winx64r\flying_start_share000.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx64r\flying_start_share000.lib" /MACHINE:X64 %PROCTS_DIR%\share000\obj\flying_start\winx64r\flying_start.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86d
mkdir obj\flying_start\winx86d
cd comp\flying_start
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../../share000/intf /ZI /nologo /W3 /WX- /diagnostics:classic /Od /Oy- /D WIN32 /D _DEBUG /D _CONSOLE /D "TARGET_DIR=\"winx86d\"" /D WIN32 /D _DEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\flying_start\winx86d\\" /Fd"%PROCTS_DIR%\share000\obj\flying_start\winx86d\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86d\flying_start_share000.exe" /INCREMENTAL /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/git2/winx86d /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/ssh2/winx86d /LIBPATH:%PROCTS_DIR%\share000\../share000/tgt/winx86d repo.lib git2.lib libssh2.lib crypt32.lib rpcrt4.lib winhttp.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FASTLINK /PDB:"%PROCTS_DIR%\share000\tgt\winx86d\flying_start_share000.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86d\flying_start_share000.lib" /MACHINE:X86 %PROCTS_DIR%\share000\obj\flying_start\winx86d\flying_start.obj
cd ..\..
SET PATH=%MSC_BIN_BASE%Hostx86\x86;%SDK_BIN_BASE%x86;
SET LIB=%MSC_LIB_BASE%x86;%SDK_LIB_BASE%ucrt\x86;%SDK_LIB_BASE%um\x86;
mkdir tgt\winx86r
mkdir obj\flying_start\winx86r
cd comp\flying_start
"%MSC_BIN_BASE%HostX86\x86\CL.exe" /c /I../../../share000/intf /Zi /nologo /W3 /WX- /diagnostics:classic /O2 /Oi /Oy- /GL /D WIN32 /D NDEBUG /D _CONSOLE /D "TARGET_DIR=\"winx86r\"" /D WIN32 /D NDEBUG /D _CONSOLE /D _UNICODE /D UNICODE /Gm- /EHsc /MD /GS /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /std:c++latest /Fo"%PROCTS_DIR%\share000\obj\flying_start\winx86r\\" /Fd"%PROCTS_DIR%\share000\obj\flying_start\winx86r\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:prompt flying_start.cpp
"%MSC_BIN_BASE%HostX86\x86\link.exe" /ERRORREPORT:PROMPT /OUT:"%PROCTS_DIR%\share000\tgt\winx86r\flying_start_share000.exe" /INCREMENTAL:NO /NOLOGO /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/git2/winx86r /LIBPATH:%PROCTS_DIR%\share000\../share000/ext/lib/ssh2/winx86r /LIBPATH:%PROCTS_DIR%\share000\../share000/tgt/winx86r repo.lib git2.lib libssh2.lib crypt32.lib rpcrt4.lib winhttp.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG:FULL /PDB:"%PROCTS_DIR%\share000\tgt\winx86r\flying_start_share000.pdb" /SUBSYSTEM:CONSOLE /OPT:REF /OPT:ICF /LTCG:incremental /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"%PROCTS_DIR%\share000\tgt\winx86r\flying_start_share000.lib" /MACHINE:X86 /SAFESEH %PROCTS_DIR%\share000\obj\flying_start\winx86r\flying_start.obj
cd ..\..
cd tgt\fig
call ..\winx86r\fig_cppmake_test_executor_nothing_to_build_uml_sd.exe
cd ..\..
cd comp\doc_cppmake
call make.cmd
cd ..\..
cd comp\doc_git
call make.cmd
cd ..\..
cd comp\doc_latex
call make.cmd
cd ..\..
cd comp\doc_libgitssh
call make.cmd
cd ..\..
cd comp\doc_scrum
call make.cmd
cd ..\..
cd comp\doc_template_beamer
call make.cmd
cd ..\..
cd comp\doc_template_book
call make.cmd
cd ..\..
cd comp\doc_usb_repo
call make.cmd
cd ..\..
set result=SUCCEEDED
cd tgt\winx64r
call test.exe
if %errorlevel% NEQ 0 set result=FAILED
cd ..\..
cd tgt\winx86r
call test.exe
if %errorlevel% NEQ 0 set result=FAILED
cd ..\..
echo == All Tests: %result% ===============================================
